name: advent_of_code_2021
description: Solutions for Advent of Code 2021.
version: 0.0.1

environment:
  sdk: "^3.5.0"

dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
