name: advent_of_code_2021
description: Solutions for Advent of Code 2021.
version: 0.0.1

environment:
  sdk: "^3.0.0"

dependencies:
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.3
